### ISSUE TITLE
Use of uninitialized value in string eq at ./bdsm-info line {480, 735, 577, 580, 583}

### ISSUE THREAD

**Issue by valerytschopp** [sleinen/diskonade#45]
On `zhdk0206.zhdk`, the latest version of `bdsm-info` throws a lot of `Use of uninitalized value ...`.

In the output, the `Disk serial number:`, `WWN:`, and `OSD Number:` values are not correctly extracted.

```
tschopp@zhdk0206:~$ sudo ./bdsm-info
Use of uninitialized value in string eq at ./bdsm-info line 480.
Use of uninitialized value in string eq at ./bdsm-info line 480.
Use of uninitialized value in string eq at ./bdsm-info line 480.
Use of uninitialized value in string eq at ./bdsm-info line 480.
Use of uninitialized value in string eq at ./bdsm-info line 480.
Use of uninitialized value in string eq at ./bdsm-info line 480.
Use of uninitialized value in string eq at ./bdsm-info line 480.
Use of uninitialized value in string eq at ./bdsm-info line 480.
Use of uninitialized value in string eq at ./bdsm-info line 480.
Use of uninitialized value in string eq at ./bdsm-info line 480.
Use of uninitialized value in string eq at ./bdsm-info line 480.
Use of uninitialized value $osd_dev in concatenation (.) or string at ./bdsm-info line 735.
the required argument for option '--dev' is missing
Create a ticket by sending a mail along these lines:

------------------------------ SNIP ------------------------------
To: <SUPER-SECRET-TICKET-SYSTEM-ADDRESS@EXAMPLE.COM>
Use of uninitialized value in printf at ./bdsm-info line 577.
Subject: zhdk0206  (sdh) disk errors

Server serial number:  C80201H29A40175
Use of uninitialized value in printf at ./bdsm-info line 580.
Disk serial number:    
Use of uninitialized value in printf at ./bdsm-info line 583.
WWN:                   
Target:                5:0:5:0
OSD Type:              BlueStore
OSD Number:            

From /var/log/kern.log:

  May  5 05:06:26 zhdk0206 kernel: [7982040.962287] sd 5:0:5:0: [sdh] tag#2 FAILED Result: hostbyte=DID_NO_CONNECT driverbyte=DRIVER_OK
  May  5 05:06:26 zhdk0206 kernel: [7982040.962294] sd 5:0:5:0: [sdh] tag#2 CDB: Write(16) 8a 00 00 00 00 03 37 4b a0 80 00 00 04 00 00 00
  May  5 05:06:26 zhdk0206 kernel: [7982040.962297] print_req_error: I/O error, dev sdh, sector 13812605056
  May  5 05:06:26 zhdk0206 kernel: [7982040.968885] print_req_error: I/O error, dev sdh, sector 13812600960
  May  5 05:06:26 zhdk0206 kernel: [7982040.975435] print_req_error: I/O error, dev sdh, sector 13812603008
  May  5 05:06:26 zhdk0206 kernel: [7982040.981970] print_req_error: I/O error, dev sdh, sector 13812601984
  May  5 05:06:26 zhdk0206 kernel: [7982040.988505] print_req_error: I/O error, dev sdh, sector 13812604032
  May  5 05:06:26 zhdk0206 kernel: [7982040.995038] print_req_error: I/O error, dev sdh, sector 13812606080
  May  5 05:06:26 zhdk0206 kernel: [7982041.001564] print_req_error: I/O error, dev sdh, sector 0
  May  5 05:06:26 zhdk0206 kernel: [7982041.007227] print_req_error: I/O error, dev sdh, sector 7523497016
  May  5 05:06:26 zhdk0206 kernel: [7982041.013667] print_req_error: I/O error, dev sdh, sector 11445554960
  May  5 05:06:26 zhdk0206 kernel: [7982041.020197] print_req_error: I/O error, dev sdh, sector 6683416192
------------------------------ SNIP ------------------------------

Now surf to

https://wiki.smap.switch.ch/topic/switchcloud/trouble_log?do=edit&rev=

 and write something like:

Use of uninitialized value in printf at ./bdsm-info line 671.
====== May  5 05:06:26 zhdk0206  (sdh) disk errors ======

[[https://ticket.switch.ch/rt/Ticket/Display.html?id=XXX|#XXX]]
```

**Comment by sleinen** [comment]
I think I have fixed most of these in recent changes.

**Comment by valerytschopp** [comment]
Unfortunately, with the latest version, I still get messages like:
* `Use of uninitialized value in string eq at ./bdsm-info line 530.`
* `Use of uninitialized value $osd_dev in concatenation (.) or string at ./bdsm-info line 808.`
* `the required argument for option '--dev' is missing`
* `Use of uninitialized value in printf at ./bdsm-info line 744.`

```
tschopp@zhdk0206:~$ ./bdsm-info
Use of uninitialized value in string eq at ./bdsm-info line 530.
Use of uninitialized value in string eq at ./bdsm-info line 530.
Use of uninitialized value in string eq at ./bdsm-info line 530.
Use of uninitialized value in string eq at ./bdsm-info line 530.
Use of uninitialized value in string eq at ./bdsm-info line 530.
Use of uninitialized value in string eq at ./bdsm-info line 530.
Use of uninitialized value in string eq at ./bdsm-info line 530.
Use of uninitialized value in string eq at ./bdsm-info line 530.
Use of uninitialized value in string eq at ./bdsm-info line 530.
Use of uninitialized value in string eq at ./bdsm-info line 530.
Use of uninitialized value in string eq at ./bdsm-info line 530.
Use of uninitialized value $osd_dev in concatenation (.) or string at ./bdsm-info line 808.
the required argument for option '--dev' is missing
Create a ticket by sending a mail along these lines:

------------------------------ SNIP ------------------------------
To: <SUPER-SECRET-TICKET-SYSTEM-ADDRESS@EXAMPLE.COM>
Subject: zhdk0206 <UNKNOWN SERIAL> (sdh) disk errors

Server serial number:  C80201H29A40175
Target:                5:0:5:0
OSD Type:              BlueStore
OSD Number:            

From /var/log/kern.log:

  May  5 05:06:26 zhdk0206 kernel: [7982040.962287] sd 5:0:5:0: [sdh] tag#2 FAILED Result: hostbyte=DID_NO_CONNECT driverbyte=DRIVER_OK
  May  5 05:06:26 zhdk0206 kernel: [7982040.962294] sd 5:0:5:0: [sdh] tag#2 CDB: Write(16) 8a 00 00 00 00 03 37 4b a0 80 00 00 04 00 00 00
  May  5 05:06:26 zhdk0206 kernel: [7982040.962297] print_req_error: I/O error, dev sdh, sector 13812605056
  May  5 05:06:26 zhdk0206 kernel: [7982040.968885] print_req_error: I/O error, dev sdh, sector 13812600960
  May  5 05:06:26 zhdk0206 kernel: [7982040.975435] print_req_error: I/O error, dev sdh, sector 13812603008
  May  5 05:06:26 zhdk0206 kernel: [7982040.981970] print_req_error: I/O error, dev sdh, sector 13812601984
  May  5 05:06:26 zhdk0206 kernel: [7982040.988505] print_req_error: I/O error, dev sdh, sector 13812604032
  May  5 05:06:26 zhdk0206 kernel: [7982040.995038] print_req_error: I/O error, dev sdh, sector 13812606080
  May  5 05:06:26 zhdk0206 kernel: [7982041.001564] print_req_error: I/O error, dev sdh, sector 0
  May  5 05:06:26 zhdk0206 kernel: [7982041.007227] print_req_error: I/O error, dev sdh, sector 7523497016
  May  5 05:06:26 zhdk0206 kernel: [7982041.013667] print_req_error: I/O error, dev sdh, sector 11445554960
  May  5 05:06:26 zhdk0206 kernel: [7982041.020197] print_req_error: I/O error, dev sdh, sector 6683416192
------------------------------ SNIP ------------------------------

Now surf to

https://wiki.smap.switch.ch/topic/switchcloud/trouble_log?do=edit&rev=

 and write something like:

Use of uninitialized value in printf at ./bdsm-info line 744.
====== May  5 05:06:26 zhdk0206  (sdh) disk errors ======

[[https://ticket.switch.ch/rt/Ticket/Display.html?id=XXX|#XXX]]

tschopp@zhdk0206:~$ 
```
